name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository incl. submodule
      uses: actions/checkout@v3
      with:
        submodules: recursive 
        
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'
  
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2 
      with:
        msbuild-architecture: x64

    - name: Restore NuGet packages
      run: nuget restore .\GeusGameEngine\GeusGameEngine.sln
      
    - name: Build 
      run: msbuild .\GeusGameEngine\GeusGameEngine.sln /p:Configuration=Release /p:Platform="x64"
      
    - name: Test
      run: .\GeusGameEngine\x64\Release\GeusGameEngine.Test.exe
